// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: simlog.proto

package demopb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SimService_GetSimLog_FullMethodName        = "/demo.SimService/GetSimLog"
	SimService_StreamObjectLogs_FullMethodName = "/demo.SimService/StreamObjectLogs"
)

// SimServiceClient is the client API for SimService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SimServiceClient interface {
	// 1メッセージで全体を返す(パターン1・2用)
	GetSimLog(ctx context.Context, in *GetSimLogRequest, opts ...grpc.CallOption) (*SimLog, error)
	// ObjectLogを1件ずつ流す(パターン3用)
	StreamObjectLogs(ctx context.Context, in *GetSimLogRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ObjectLog], error)
}

type simServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSimServiceClient(cc grpc.ClientConnInterface) SimServiceClient {
	return &simServiceClient{cc}
}

func (c *simServiceClient) GetSimLog(ctx context.Context, in *GetSimLogRequest, opts ...grpc.CallOption) (*SimLog, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SimLog)
	err := c.cc.Invoke(ctx, SimService_GetSimLog_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *simServiceClient) StreamObjectLogs(ctx context.Context, in *GetSimLogRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ObjectLog], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SimService_ServiceDesc.Streams[0], SimService_StreamObjectLogs_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GetSimLogRequest, ObjectLog]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SimService_StreamObjectLogsClient = grpc.ServerStreamingClient[ObjectLog]

// SimServiceServer is the server API for SimService service.
// All implementations must embed UnimplementedSimServiceServer
// for forward compatibility.
type SimServiceServer interface {
	// 1メッセージで全体を返す(パターン1・2用)
	GetSimLog(context.Context, *GetSimLogRequest) (*SimLog, error)
	// ObjectLogを1件ずつ流す(パターン3用)
	StreamObjectLogs(*GetSimLogRequest, grpc.ServerStreamingServer[ObjectLog]) error
	mustEmbedUnimplementedSimServiceServer()
}

// UnimplementedSimServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSimServiceServer struct{}

func (UnimplementedSimServiceServer) GetSimLog(context.Context, *GetSimLogRequest) (*SimLog, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSimLog not implemented")
}
func (UnimplementedSimServiceServer) StreamObjectLogs(*GetSimLogRequest, grpc.ServerStreamingServer[ObjectLog]) error {
	return status.Error(codes.Unimplemented, "method StreamObjectLogs not implemented")
}
func (UnimplementedSimServiceServer) mustEmbedUnimplementedSimServiceServer() {}
func (UnimplementedSimServiceServer) testEmbeddedByValue()                    {}

// UnsafeSimServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SimServiceServer will
// result in compilation errors.
type UnsafeSimServiceServer interface {
	mustEmbedUnimplementedSimServiceServer()
}

func RegisterSimServiceServer(s grpc.ServiceRegistrar, srv SimServiceServer) {
	// If the following call panics, it indicates UnimplementedSimServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SimService_ServiceDesc, srv)
}

func _SimService_GetSimLog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSimLogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SimServiceServer).GetSimLog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SimService_GetSimLog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SimServiceServer).GetSimLog(ctx, req.(*GetSimLogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SimService_StreamObjectLogs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetSimLogRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SimServiceServer).StreamObjectLogs(m, &grpc.GenericServerStream[GetSimLogRequest, ObjectLog]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SimService_StreamObjectLogsServer = grpc.ServerStreamingServer[ObjectLog]

// SimService_ServiceDesc is the grpc.ServiceDesc for SimService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SimService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "demo.SimService",
	HandlerType: (*SimServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSimLog",
			Handler:    _SimService_GetSimLog_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamObjectLogs",
			Handler:       _SimService_StreamObjectLogs_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "simlog.proto",
}
