// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: simlog.proto

package demopb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SimLog struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         int64                  `protobuf:"varint,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Logs          []*ObjectLog           `protobuf:"bytes,2,rep,name=logs,proto3" json:"logs,omitempty"`
	Result        *Result                `protobuf:"bytes,3,opt,name=result,proto3,oneof" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SimLog) Reset() {
	*x = SimLog{}
	mi := &file_simlog_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SimLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimLog) ProtoMessage() {}

func (x *SimLog) ProtoReflect() protoreflect.Message {
	mi := &file_simlog_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimLog.ProtoReflect.Descriptor instead.
func (*SimLog) Descriptor() ([]byte, []int) {
	return file_simlog_proto_rawDescGZIP(), []int{0}
}

func (x *SimLog) GetJobId() int64 {
	if x != nil {
		return x.JobId
	}
	return 0
}

func (x *SimLog) GetLogs() []*ObjectLog {
	if x != nil {
		return x.Logs
	}
	return nil
}

func (x *SimLog) GetResult() *Result {
	if x != nil {
		return x.Result
	}
	return nil
}

type ObjectLog struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	ObjectId      int64                  `protobuf:"varint,2,opt,name=object_id,json=objectId,proto3" json:"object_id,omitempty"`
	Events        []*Event               `protobuf:"bytes,3,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ObjectLog) Reset() {
	*x = ObjectLog{}
	mi := &file_simlog_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObjectLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectLog) ProtoMessage() {}

func (x *ObjectLog) ProtoReflect() protoreflect.Message {
	mi := &file_simlog_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectLog.ProtoReflect.Descriptor instead.
func (*ObjectLog) Descriptor() ([]byte, []int) {
	return file_simlog_proto_rawDescGZIP(), []int{1}
}

func (x *ObjectLog) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *ObjectLog) GetObjectId() int64 {
	if x != nil {
		return x.ObjectId
	}
	return 0
}

func (x *ObjectLog) GetEvents() []*Event {
	if x != nil {
		return x.Events
	}
	return nil
}

type Result struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExitCode      int64                  `protobuf:"varint,1,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	Output        string                 `protobuf:"bytes,2,opt,name=output,proto3" json:"output,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Result) Reset() {
	*x = Result{}
	mi := &file_simlog_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Result) ProtoMessage() {}

func (x *Result) ProtoReflect() protoreflect.Message {
	mi := &file_simlog_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Result.ProtoReflect.Descriptor instead.
func (*Result) Descriptor() ([]byte, []int) {
	return file_simlog_proto_rawDescGZIP(), []int{2}
}

func (x *Result) GetExitCode() int64 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *Result) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

type Event struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	EventId   int64                  `protobuf:"varint,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	EventType int64                  `protobuf:"varint,2,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*Event_CommEvent
	//	*Event_ExecEvent
	Payload       isEvent_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_simlog_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_simlog_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_simlog_proto_rawDescGZIP(), []int{3}
}

func (x *Event) GetEventId() int64 {
	if x != nil {
		return x.EventId
	}
	return 0
}

func (x *Event) GetEventType() int64 {
	if x != nil {
		return x.EventType
	}
	return 0
}

func (x *Event) GetPayload() isEvent_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Event) GetCommEvent() *CommEvent {
	if x != nil {
		if x, ok := x.Payload.(*Event_CommEvent); ok {
			return x.CommEvent
		}
	}
	return nil
}

func (x *Event) GetExecEvent() *ExecEvent {
	if x != nil {
		if x, ok := x.Payload.(*Event_ExecEvent); ok {
			return x.ExecEvent
		}
	}
	return nil
}

type isEvent_Payload interface {
	isEvent_Payload()
}

type Event_CommEvent struct {
	CommEvent *CommEvent `protobuf:"bytes,3,opt,name=comm_event,json=commEvent,proto3,oneof"`
}

type Event_ExecEvent struct {
	ExecEvent *ExecEvent `protobuf:"bytes,4,opt,name=exec_event,json=execEvent,proto3,oneof"`
}

func (*Event_CommEvent) isEvent_Payload() {}

func (*Event_ExecEvent) isEvent_Payload() {}

type CommEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromId        int64                  `protobuf:"varint,1,opt,name=from_id,json=fromId,proto3" json:"from_id,omitempty"`
	ToId          int64                  `protobuf:"varint,2,opt,name=to_id,json=toId,proto3" json:"to_id,omitempty"`
	Body          string                 `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommEvent) Reset() {
	*x = CommEvent{}
	mi := &file_simlog_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommEvent) ProtoMessage() {}

func (x *CommEvent) ProtoReflect() protoreflect.Message {
	mi := &file_simlog_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommEvent.ProtoReflect.Descriptor instead.
func (*CommEvent) Descriptor() ([]byte, []int) {
	return file_simlog_proto_rawDescGZIP(), []int{4}
}

func (x *CommEvent) GetFromId() int64 {
	if x != nil {
		return x.FromId
	}
	return 0
}

func (x *CommEvent) GetToId() int64 {
	if x != nil {
		return x.ToId
	}
	return 0
}

func (x *CommEvent) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

type ExecEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExecId        int64                  `protobuf:"varint,1,opt,name=exec_id,json=execId,proto3" json:"exec_id,omitempty"`
	Command       string                 `protobuf:"bytes,2,opt,name=command,proto3" json:"command,omitempty"`
	Result        string                 `protobuf:"bytes,3,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecEvent) Reset() {
	*x = ExecEvent{}
	mi := &file_simlog_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecEvent) ProtoMessage() {}

func (x *ExecEvent) ProtoReflect() protoreflect.Message {
	mi := &file_simlog_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecEvent.ProtoReflect.Descriptor instead.
func (*ExecEvent) Descriptor() ([]byte, []int) {
	return file_simlog_proto_rawDescGZIP(), []int{5}
}

func (x *ExecEvent) GetExecId() int64 {
	if x != nil {
		return x.ExecId
	}
	return 0
}

func (x *ExecEvent) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *ExecEvent) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

type GetSimLogRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	IncludeResult   bool                   `protobuf:"varint,1,opt,name=include_result,json=includeResult,proto3" json:"include_result,omitempty"`         // trueならresultを設定する
	ObjectCount     int32                  `protobuf:"varint,2,opt,name=object_count,json=objectCount,proto3" json:"object_count,omitempty"`               // ObjectLogの件数
	EventsPerObject int32                  `protobuf:"varint,3,opt,name=events_per_object,json=eventsPerObject,proto3" json:"events_per_object,omitempty"` // 1ObjectLogあたりのEvent数
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetSimLogRequest) Reset() {
	*x = GetSimLogRequest{}
	mi := &file_simlog_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSimLogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSimLogRequest) ProtoMessage() {}

func (x *GetSimLogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_simlog_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSimLogRequest.ProtoReflect.Descriptor instead.
func (*GetSimLogRequest) Descriptor() ([]byte, []int) {
	return file_simlog_proto_rawDescGZIP(), []int{6}
}

func (x *GetSimLogRequest) GetIncludeResult() bool {
	if x != nil {
		return x.IncludeResult
	}
	return false
}

func (x *GetSimLogRequest) GetObjectCount() int32 {
	if x != nil {
		return x.ObjectCount
	}
	return 0
}

func (x *GetSimLogRequest) GetEventsPerObject() int32 {
	if x != nil {
		return x.EventsPerObject
	}
	return 0
}

var File_simlog_proto protoreflect.FileDescriptor

const file_simlog_proto_rawDesc = "" +
	"\n" +
	"\fsimlog.proto\x12\x04demo\"z\n" +
	"\x06SimLog\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\x03R\x05jobId\x12#\n" +
	"\x04logs\x18\x02 \x03(\v2\x0f.demo.ObjectLogR\x04logs\x12)\n" +
	"\x06result\x18\x03 \x01(\v2\f.demo.ResultH\x00R\x06result\x88\x01\x01B\t\n" +
	"\a_result\"k\n" +
	"\tObjectLog\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\x12\x1b\n" +
	"\tobject_id\x18\x02 \x01(\x03R\bobjectId\x12#\n" +
	"\x06events\x18\x03 \x03(\v2\v.demo.EventR\x06events\"=\n" +
	"\x06Result\x12\x1b\n" +
	"\texit_code\x18\x01 \x01(\x03R\bexitCode\x12\x16\n" +
	"\x06output\x18\x02 \x01(\tR\x06output\"\xb0\x01\n" +
	"\x05Event\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\x03R\aeventId\x12\x1d\n" +
	"\n" +
	"event_type\x18\x02 \x01(\x03R\teventType\x120\n" +
	"\n" +
	"comm_event\x18\x03 \x01(\v2\x0f.demo.CommEventH\x00R\tcommEvent\x120\n" +
	"\n" +
	"exec_event\x18\x04 \x01(\v2\x0f.demo.ExecEventH\x00R\texecEventB\t\n" +
	"\apayload\"M\n" +
	"\tCommEvent\x12\x17\n" +
	"\afrom_id\x18\x01 \x01(\x03R\x06fromId\x12\x13\n" +
	"\x05to_id\x18\x02 \x01(\x03R\x04toId\x12\x12\n" +
	"\x04body\x18\x03 \x01(\tR\x04body\"V\n" +
	"\tExecEvent\x12\x17\n" +
	"\aexec_id\x18\x01 \x01(\x03R\x06execId\x12\x18\n" +
	"\acommand\x18\x02 \x01(\tR\acommand\x12\x16\n" +
	"\x06result\x18\x03 \x01(\tR\x06result\"\x88\x01\n" +
	"\x10GetSimLogRequest\x12%\n" +
	"\x0einclude_result\x18\x01 \x01(\bR\rincludeResult\x12!\n" +
	"\fobject_count\x18\x02 \x01(\x05R\vobjectCount\x12*\n" +
	"\x11events_per_object\x18\x03 \x01(\x05R\x0feventsPerObject2~\n" +
	"\n" +
	"SimService\x121\n" +
	"\tGetSimLog\x12\x16.demo.GetSimLogRequest\x1a\f.demo.SimLog\x12=\n" +
	"\x10StreamObjectLogs\x12\x16.demo.GetSimLogRequest\x1a\x0f.demo.ObjectLog0\x01B!\n" +
	"\n" +
	"demo.protoP\x01Z\x11demo/proto;demopbb\x06proto3"

var (
	file_simlog_proto_rawDescOnce sync.Once
	file_simlog_proto_rawDescData []byte
)

func file_simlog_proto_rawDescGZIP() []byte {
	file_simlog_proto_rawDescOnce.Do(func() {
		file_simlog_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_simlog_proto_rawDesc), len(file_simlog_proto_rawDesc)))
	})
	return file_simlog_proto_rawDescData
}

var file_simlog_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_simlog_proto_goTypes = []any{
	(*SimLog)(nil),           // 0: demo.SimLog
	(*ObjectLog)(nil),        // 1: demo.ObjectLog
	(*Result)(nil),           // 2: demo.Result
	(*Event)(nil),            // 3: demo.Event
	(*CommEvent)(nil),        // 4: demo.CommEvent
	(*ExecEvent)(nil),        // 5: demo.ExecEvent
	(*GetSimLogRequest)(nil), // 6: demo.GetSimLogRequest
}
var file_simlog_proto_depIdxs = []int32{
	1, // 0: demo.SimLog.logs:type_name -> demo.ObjectLog
	2, // 1: demo.SimLog.result:type_name -> demo.Result
	3, // 2: demo.ObjectLog.events:type_name -> demo.Event
	4, // 3: demo.Event.comm_event:type_name -> demo.CommEvent
	5, // 4: demo.Event.exec_event:type_name -> demo.ExecEvent
	6, // 5: demo.SimService.GetSimLog:input_type -> demo.GetSimLogRequest
	6, // 6: demo.SimService.StreamObjectLogs:input_type -> demo.GetSimLogRequest
	0, // 7: demo.SimService.GetSimLog:output_type -> demo.SimLog
	1, // 8: demo.SimService.StreamObjectLogs:output_type -> demo.ObjectLog
	7, // [7:9] is the sub-list for method output_type
	5, // [5:7] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_simlog_proto_init() }
func file_simlog_proto_init() {
	if File_simlog_proto != nil {
		return
	}
	file_simlog_proto_msgTypes[0].OneofWrappers = []any{}
	file_simlog_proto_msgTypes[3].OneofWrappers = []any{
		(*Event_CommEvent)(nil),
		(*Event_ExecEvent)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_simlog_proto_rawDesc), len(file_simlog_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_simlog_proto_goTypes,
		DependencyIndexes: file_simlog_proto_depIdxs,
		MessageInfos:      file_simlog_proto_msgTypes,
	}.Build()
	File_simlog_proto = out.File
	file_simlog_proto_goTypes = nil
	file_simlog_proto_depIdxs = nil
}
